/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.hp.computer.app.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Computer service. Represents a row in the &quot;CMP_Computer&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hp.computer.app.model.impl.ComputerModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hp.computer.app.model.impl.ComputerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Computer
 * @see com.hp.computer.app.model.impl.ComputerImpl
 * @see com.hp.computer.app.model.impl.ComputerModelImpl
 * @generated
 */
@ProviderType
public interface ComputerModel extends BaseModel<Computer>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a computer model instance should use the {@link Computer} interface instead.
	 */

	/**
	 * Returns the primary key of this computer.
	 *
	 * @return the primary key of this computer
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this computer.
	 *
	 * @param primaryKey the primary key of this computer
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this computer.
	 *
	 * @return the uuid of this computer
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this computer.
	 *
	 * @param uuid the uuid of this computer
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the computer ID of this computer.
	 *
	 * @return the computer ID of this computer
	 */
	public long getComputerId();

	/**
	 * Sets the computer ID of this computer.
	 *
	 * @param computerId the computer ID of this computer
	 */
	public void setComputerId(long computerId);

	/**
	 * Returns the group ID of this computer.
	 *
	 * @return the group ID of this computer
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this computer.
	 *
	 * @param groupId the group ID of this computer
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this computer.
	 *
	 * @return the company ID of this computer
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this computer.
	 *
	 * @param companyId the company ID of this computer
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this computer.
	 *
	 * @return the user ID of this computer
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this computer.
	 *
	 * @param userId the user ID of this computer
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this computer.
	 *
	 * @return the user uuid of this computer
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this computer.
	 *
	 * @param userUuid the user uuid of this computer
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this computer.
	 *
	 * @return the user name of this computer
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this computer.
	 *
	 * @param userName the user name of this computer
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this computer.
	 *
	 * @return the create date of this computer
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this computer.
	 *
	 * @param createDate the create date of this computer
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this computer.
	 *
	 * @return the modified date of this computer
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this computer.
	 *
	 * @param modifiedDate the modified date of this computer
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the company of this computer.
	 *
	 * @return the company of this computer
	 */
	@AutoEscape
	public String getCompany();

	/**
	 * Sets the company of this computer.
	 *
	 * @param company the company of this computer
	 */
	public void setCompany(String company);

	/**
	 * Returns the model name of this computer.
	 *
	 * @return the model name of this computer
	 */
	@AutoEscape
	public String getModelName();

	/**
	 * Sets the model name of this computer.
	 *
	 * @param modelName the model name of this computer
	 */
	public void setModelName(String modelName);

	/**
	 * Returns the operating system of this computer.
	 *
	 * @return the operating system of this computer
	 */
	@AutoEscape
	public String getOperatingSystem();

	/**
	 * Sets the operating system of this computer.
	 *
	 * @param operatingSystem the operating system of this computer
	 */
	public void setOperatingSystem(String operatingSystem);

	/**
	 * Returns the cost of this computer.
	 *
	 * @return the cost of this computer
	 */
	public double getCost();

	/**
	 * Sets the cost of this computer.
	 *
	 * @param cost the cost of this computer
	 */
	public void setCost(double cost);

	/**
	 * Returns the rating of this computer.
	 *
	 * @return the rating of this computer
	 */
	public int getRating();

	/**
	 * Sets the rating of this computer.
	 *
	 * @param rating the rating of this computer
	 */
	public void setRating(int rating);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Computer computer);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Computer> toCacheModel();

	@Override
	public Computer toEscapedModel();

	@Override
	public Computer toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}